Add Basic Functionality Test
liatrio/ldop-docker-compose pull request #10
Opened 2017-06-08 23:18 UTC by shanemacbride

Implemented `/adop test basic`:
  - runs `/adop compose down --volumes`
  - runs `/adop compose init --without-load`
  - triggers `Load_Platform` job to run
  - checks the states of containers that are not running
  - outputs the results (Load_Platform build result, container names and statuses that are not running)

Example Output from `/adop test basic`:
```
#######################
#  Testing Results:   #
#######################

Load_Platform Build Result: SUCCESS

Docker Containers with Non-running Statuses:
registry: Restarting (1) About a minute ago

```

2017-06-09 00:51 UTC, ghost requested changes
Some additional items to implement added to JIRA.

2017-06-12 17:26 UTC, shanemacbride commented
#### Requested Changes Implemented

Example test output:
```
Removing volume ldopdockercompose_test_sensu_rabbitmq_data
Removing volume ldopdockercompose_test_sonar_data
Removing volume ldopdockercompose_test_ldap_static
Removing volume ldopdockercompose_test_sensu_client_conf
Removing volume ldopdockercompose_test_ldap_db
Removing volume ldopdockercompose_test_nginx_config
Removing volume ldopdockercompose_test_sonar_mysql_data
Removing volume ldopdockercompose_test_sonar_extensions
Removing volume ldopdockercompose_test_jenkins_home
Removing volume ldopdockercompose_test_elasticsearch_data
Removing volume ldopdockercompose_test_registry_data
Removing volume ldopdockercompose_test_sonar_logs
Removing volume ldopdockercompose_test_sensu_redis_data
Removing volume ldopdockercompose_test_jenkins_slave_home
Removing volume ldopdockercompose_test_sensu_api_conf
Removing volume ldopdockercompose_test_nexus_sonatype_work
Removing volume ldopdockercompose_test_gerrit_review_site
Removing volume ldopdockercompose_test_git_repos
Removing volume ldopdockercompose_test_nginx_releasenote
Removing volume ldopdockercompose_test_gerrit_mysql_data
Removing volume ldopdockercompose_test_registry_certs
Removing volume ldopdockercompose_test_sensu_server_conf

#######################
#  Testing Results:   #
#######################


Load_Platform Build Result: SUCCESS

Docker Containers with Non-running Statuses:

registry: Restarting (1) 46 seconds ago

...basic test complete.
```

Command usage:
```
usage: adop test basic [<options>]

         Options:
          -w : Execute init without the --without-pull flag.
          -h : Prints this help information.
```

Functionality:

- Using temporary volumes, compose init --without-load --without-pull (unless -w flag)
- Trigger the Load_Platform job, wait for it to build, store the result
- Examine running containers, save name of any that are not Running/Up
- Run compose down and remove the temporary volumes
- Output the results of the test, including the build result of Load_Platform and any container with non-running status prior to compose down

2017-06-13 18:25 UTC, ghost requested changes

2017-06-13 18:25 UTC, liatriojoe commented on cmd/test
> +  PS=$(${CONF_DIR}/adop compose ps -q | wc -l)
Consider the case where something changes in the compose script as to how it performs standard output which then alters what the correct line count is. Is there a way we can instead parse the State field of the compose command and check for running (or other states where we want to prompt)?

2017-06-13 18:42 UTC, shanemacbride commented on cmd/test
> +  PS=$(${CONF_DIR}/adop compose ps -q | wc -l)
replied in person

2017-06-13 21:57 UTC, ghost requested changes

2017-06-13 21:57 UTC, liatriojoe commented on cmd/test
> +    if [ "${#AFTER_HEADER}" -gt "0" ]
This doesn't handle the case where the platform is paused, as stopping is not a permitted operation on a paused container.

Sample error output: ERROR: for elasticsearch  Cannot stop container 6c6cf14118ae2702ddf066f66805e505e79940a785a7df7ee2cc150549c8cd6a: Container 6c6cf14118ae2702ddf066f66805e505e79940a785a7df7ee2cc150549c8cd6a is paused. Unpause the container before stopping

2017-06-14 16:38 UTC, ghost requested changes

2017-06-14 16:38 UTC, liatriojoe commented on cmd/test
> +        ${CONF_DIR}/adop compose unpause 2>/dev/null
Would like to test for a particular condition to determine whether running a command is necessary as opposed to just forcing it and hiding output. 

For example, parse output to determine whether there are any paused containers, and if so, unpause them. If there are not any paused containers, then there's no need to unpause. Should also allow us to surface output from unpause/down commands which could be useful to either users of this command or logs in a CI/CD system should some unexpected scenario arise.

2017-06-14 23:26 UTC, ghost approved these changes

2017-06-14 23:28 UTC, merged